version: "3"

networks:
    my-network:
      driver: bridge

services:
    mqtt:
        image: toke/mosquitto
        container_name: mqtt
        ports:
        - 1883:1883
        restart: unless-stopped
        networks:
            - my-network
    influxdb:
        image: bitnami/influxdb:latest
        environment:
            - INFLUXDB_HTTP_AUTH_ENABLED=false
            - INFLUXDB_ADMIN_USER_PASSWORD=password123
            - INFLUXDB_DB=honey_data
        networks:
            - my-network