version: "3"

networks:
    my-network:
      driver: bridge

volumes:
    influxdb:

services:
    mqtt:
        image: toke/mosquitto
        ports:
        - 1883:1883
        restart: unless-stopped
        networks:
            - my-network
    influxdb:
        image: influxdb:latest
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_HTTP_AUTH_ENABLED=false
            - INFLUXDB_DB=honeycomb2
            - INFLUXDB_USER=root
            - INFLUXDB_USER_PASSWORD=root
        networks:
            - my-network
        volumes:
            - influxdb:/var/lib/influxdb
    web:
        build: ./web
        ports:
            - 5000:5000
        depends_on:
            - backend
        networks:
            - my-network
    backend:
        build: ./backend
        networks:
            - my-network
        depends_on:
            - mqtt
            - influxdb
